# config/mongod.conf — параметры СУБД внутри контейнера

storage:
  dbPath: /var/lib/mongodb         # место хранения данных СУБД ./data/mongodb
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1        # размер оперативки, которая будет использвоватся при работе (размер хеша)
    collectionConfig:
      blockCompressor: snappy       # метод сжатия данных

systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log   # сюда хранения логов ./data/logs
  logAppend: true       # явное указание логирования
  verbosity: 0

net:
  port: 27017       # порт на СУБД
  bindIp: 0.0.0.0       # указание что СУБД может быть использована другими

operationProfiling:
  mode: slowOp          # профилирование операций (логирование)
  slowOpThresholdMs: 100        # логирование всех опираций дольше 100 мс